import numpy as np

LOOKUP = {'ar': 'Arabic',
          'bg': 'Bulgarian',
          'de': 'German',
          'el': 'Modern Greek',
          'en': 'English',
          'es': 'Spanish',
          'fr': 'French',
          'hi': 'Hindi',
          'it': 'Italian',
          'ja': 'Japanese',
          'nl': 'Dutch',
          'pl': 'Polish',
          'pt': 'Portuguese',
          'ru': 'Russian',
          'sw': 'Swahili',
          'th': 'Thai',
          'tr': 'Turkish',
          'ur': 'Urdu',
          'vi': 'Vietnamese',
          'zh': 'Chinese'}

TB_SINGLE = {
    "en": ["distribute",
           "sulphur",
           "prayer",
           "allocation",
           "photograph",
           "screw",
           "transmission",
           "volcano",
           "dependence",
           "high"],
    "zh": ["建定",
           "钟楼",
           "钓名沽誉",
           "诽诋",
           "暗中作梗",
           "威尼斯",
           "良师益友",
           "语意",
           "酣然",
           "流劫"],
    "fr": ["citoyen",
           "chinois",
           "intolérable",
           "déguiser",
           "épouser",
           "pourquoi",
           "sacré",
           "curieux",
           "éclater",
           "français"],
    "es": ["equitación",
           "amarillo",
           "menguar",
           "desdentado",
           "agradecer",
           "infección",
           "desencadenar",
           "autorización",
           "impuesto",
           "conjunto"],
    "ru": ["болеть",
           "сущность",
           "энергетика",
           "швырнуть",
           "черепаха",
           "анализировать",
           "декабрь",
           "мотоцикл",
           "обитать",
           "установиться"]
}